# https://github.com/pypa/gh-action-pypi-publish
# https://github.com/py-why/dowhy/blob/main/.github/workflows/python-publish.yml

name: Upload Python Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3.0.0

      - name: Install Poetry Dynamic Versioning Plugin
        run: pip install poetry-dynamic-versioning

      - name: Install dependencies
        run: poetry install

      - name: Build and publish
        run: |
          poetry-dynamic-versioning
          poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
